apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-api-service-init
  namespace: openstack
data:
  openstackclient.cmds: |
    user create --domain default --password openstack nova
    project create service
    role add --project service --user nova admin
    service create --name nova --description "Openstack Compute" compute
    endpoint create --region regionOne nova public http://nova-openstack.apps.ostest.test.metalkube.org/v2.1/
    endpoint create --region regionOne nova admin http://nova-openstack.apps.ostest.test.metalkube.org/v2.1/
    endpoint create --region regionOne nova internal http://nova.openstack.svc:8774/v2.1/
