apiVersion: batch/v1
kind: Job
metadata:
  name: glance-dbsync
  namespace: openstack
spec:
  backoffLimit: 4
  template:
    metadata:
      name: glance-dbsync
      namespace: openstack
    spec:
      serviceAccountName: openstack-proto
      restartPolicy: Never
      containers:
        - name: glance-kolla
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: "COPY_ALWAYS"
            - name: KOLLA_BOOTSTRAP
              value: "TRUE"
          image: tripleotrain/rhel-binary-glance-api:current-tripleo
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /var/lib/config-data
              readOnly: true
              name: config-data
            - mountPath: /var/lib/kolla/config_files
              readOnly: true
              name: kolla-config
            - mountPath: /var/lib/glance
              name: filestore
      volumes:
        - name: kolla-config
          configMap:
            name: glance
            items:
              - key: kolla-config.json
                path: config.json
        - name: config-data
          configMap:
            name: glance
            defaultMode: 0644
            items:
              - key: glance-api.conf
                path: glance-api.conf
              - key: logging.conf
                path: logging.conf
        - name: filestore
          persistentVolumeClaim:
            claimName: glance-filestore
