apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glance-filestore
  namespace: openstack
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80G
