apiVersion: batch/v1
kind: Job
metadata:
  name: &name nova-cell1-dbcreate
  namespace: &namespace openstack
spec:
  backoffLimit: 4
  template:
    metadata:
      name: *name
      namespace: *namespace
    spec:
      restartPolicy: Never
      containers:
      - name: mariadb-client
        image: docker.io/tripleomaster/centos-binary-mariadb:current-tripleo
        env:
        - name: MYSQL_PWD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: DbRootPassword
        command:
        - /usr/bin/mysql
        - -h
        - mariadb.openstack.svc
        - -u
        - root
        - -P
        - "3306"
        - -e
        - |
          CREATE DATABASE IF NOT EXISTS nova_cell1;
          GRANT ALL PRIVILEGES ON nova_cell1.* TO 'nova-cell1'@'localhost' IDENTIFIED BY 'password';
          GRANT ALL PRIVILEGES ON nova_cell1.* TO 'nova-cell1'@'%' IDENTIFIED BY 'password';
