apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  namespace: openstack
data:
  config.json: |
    {
        "command": "/usr/lib/rabbitmq/bin/rabbitmq-server",
        "config_files": [
            {
                "source": "/var/lib/config-data/rabbitmq.conf",
                "dest": "/etc/rabbitmq/rabbitmq.conf",
                "owner": "rabbitmq",
                "perm": "0600"
            },
            {
                "source": "/var/lib/config-data/advanced.config",
                "dest": "/etc/rabbitmq/advanced.config",
                "owner": "rabbitmq",
                "perm": "0600"
            },
            {
                "source": "/var/lib/config-data/enabled_plugins",
                "dest": "/etc/rabbitmq/enabled_plugins",
                "owner": "rabbitmq",
                "perm": "0600"
            },
            {
                "source": "/var/lib/config-data/rabbitmq-env.conf",
                "dest": "/etc/rabbitmq/rabbitmq-env.conf",
                "owner": "rabbitmq",
                "perm": "0600"
            },
            {
                "source": "/var/lib/rabbitmq-cluster/cookie",
                "dest": "/var/lib/rabbitmq/.erlang.cookie",
                "owner": "rabbitmq",
                "perm": "0600"
            }
        ],
        "permissions": [
            {
                "path": "/var/lib/rabbitmq",
                "owner": "rabbitmq:rabbitmq",
                "recurse": "true"
            }
        ]
    }
  enabled_plugins: |
    [rabbitmq_peer_discovery_k8s, rabbitmq_management, rabbitmq_prometheus].
  rabbitmq.conf: |
    cluster_formation.peer_discovery_backend = k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.k8s.service_name = rabbitmq-cluster
    cluster_formation.k8s.hostname_suffix = .rabbitmq-cluster.openstack.svc.cluster.local

    queue_master_locator=min-masters

    tcp_listen_options.keepalive = true
    tcp_listen_options.backlog = 128
    tcp_listen_options.nodelay = true
    tcp_listen_options.linger.on = true
    tcp_listen_options.linger.timeout = 0
    tcp_listen_options.exit_on_close = false

    listeners.tcp.default = 5672

    log.console = true
    log.console.level = debug
    log.file = false

    collect_statistics_interval = 30000

    management.rates_mode = none
    management.tcp.port = 15672
    management.tcp.ip = 127.0.0.1

    default_user = admin
    default_pass = admin
    loopback_users.admin = true
  advanced.config: |
    [
      {kernel, [
        {inet_dist_listen_max, 25672},
        {inet_dist_listen_min, 25672},
        {net_ticktime, 15}
      ]}
    ].
  rabbitmq-env.conf: |
    RABBITMQ_SERVER_ERL_ARGS='+K true +P 1048576 -kernel inet_default_connect_options [{nodelay,true}]'
    RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS='+sbwt none'
    RABBITMQ_USE_LONGNAME=true
