apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: openstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openstack-rabbitmq
  template:
    metadata:
      name: rabbitmq
      namespace: openstack
      labels:
        app: openstack-rabbitmq
    spec:
      serviceAccountName: openstack-proto
      containers:
      - name: rabbitmq
        image: docker.io/tripleomaster/centos-binary-rabbitmq:current-tripleo
        volumeMounts:
        - mountPath: /var/lib/config-data
          readOnly: true
          name: config-data
        - mountPath: /var/lib/kolla/config_files
          readOnly: true
          name: kolla-config
        - mountPath: /var/lib/rabbitmq
          name: lib-data
        env:
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
      volumes:
      - name: kolla-config
        configMap:
          name: rabbitmq
          items:
            - key: config.json
              path: config.json
      - name: config-data
        configMap:
          name: rabbitmq
          items:
            - key: rabbitmq.config
              path: rabbitmq.config
            - key: rabbitmq-env.conf
              path: rabbitmq-env.conf
      - name: lib-data
        persistentVolumeClaim:
          claimName: rabbitmq
      initContainers:
      - name: rabbitmq-init
        image: docker.io/tripleomaster/centos-binary-rabbitmq:current-tripleo
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /var/lib/config-data
          readOnly: true
          name: config-data
        - mountPath: /var/lib/kolla/config_files
          readOnly: true
          name: kolla-config
        - mountPath: /var/lib/rabbitmq
          name: lib-data
        env:
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
        - name: KOLLA_BOOTSTRAP
          value: 'true'
        - name: RABBITMQ_CLUSTER_COOKIE
          value: foobar123
