apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-cluster
  namespace: openstack
spec:
  clusterIP: None
  ports:
  - name: epmd
    port: 4369
    protocol: TCP
  - name: cluster
    port: 25672
    protocol: TCP
  selector:
    app: rabbitmq
  type: ClusterIP
  sessionAffinity: None
