apiVersion: v1
kind: Service
metadata:
  name: openstack-rabbitmq
  namespace: openstack
spec:
  selector:
    app: openstack-rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
