apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-service-init
  namespace: openstack
data:
  openstackclient.cmds: |
    user create --domain default --password foobar123 glance
    project create service
    role add --project service --user glance admin
    service create --name glance --description "Openstack Image" image
    endpoint create --region regionOne image public http://glanceapi-openstack.apps.ostest.test.metalkube.org/
    endpoint create --region regionOne image admin http://glanceapi-openstack.apps.ostest.test.metalkube.org/
    endpoint create --region regionOne image internal http://glanceapi.openstack.svc:9292/
