# This role only works correctly on localhost due to the use of fetch
# It creates ~/ostest-working initially containing kubeconfig and a bin
# directory containing oc.

# Also used indirectly by default variables
- name: Include variables
  include_vars: vars/default.yaml

# We use mkdir instead of file below because the local shell always expands ~
# correctly locally, and doesn't try to change the permissions on the local
# directory to the remote user

- name: Create local environment
  block:
  - import_role: name=oc_local

  - name: Create bin directory
    file:
      path: "{{ working_bin_dir }}"
      state: directory

  - name: Create environment file
    template:
      src: oc_env.sh.j2
      dest: "{{ working_dir }}/oc_env.sh"
  become: false
  connection: local

- name: Copy kubeconfig
  fetch:
    dest: "{{ kubeconfig }}"
    src: "{{ base_path }}/dev-scripts/ocp/{{ ocp_cluster_name }}/auth/kubeconfig"
    flat: true

- name: Copy oc binary
  fetch:
    dest: "{{ working_bin_dir }}/"
    src: "/usr/local/bin/oc"
    flat: true
    mode: 0755

- name: Fix permissions on oc binary
  file:
    path: "{{ working_bin_dir }}/oc"
    mode: 0755
    state: file
  become: false
  connection: local
