apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name nova-cell1-conductor
  namespace: &namespace openstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
      namespace: *namespace
    spec:
      serviceAccountName: openstack-proto
      containers:
        - image: tripleotrain/rhel-binary-nova-conductor:current-tripleo
          name: nova-cell1-kolla
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: "COPY_ALWAYS"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /var/lib/config-data
              readOnly: true
              name: config-data
            - mountPath: /var/lib/kolla/config_files
              readOnly: true
              name: kolla-config
      volumes:
        - name: kolla-config
          configMap:
            name: nova-cell1
            items:
              - key: kolla-config-conductor.json
                path: config.json
        - name: config-data
          configMap:
            name: nova-cell1
            defaultMode: 0444
            items:
              - key: nova.conf
                path: nova.conf
              - key: logging.conf
                path: logging.conf
