apiVersion: v1
kind: ConfigMap
metadata:
  name: placement
  namespace: openstack
data:
  httpd.conf: |
    ServerTokens Prod
    ServerSignature Off
    TraceEnable Off
    ServerRoot "/etc/httpd"
    ServerName "placement.openstack.svc"

    User apache
    Group apache

    Listen 8778

    TypesConfig /etc/mime.types

    Include conf.modules.d/*.conf
    # XXX: To disable SSL
    #Include conf.d/*.conf

    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy

    SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
    CustomLog /dev/stdout combined env=!forwarded
    CustomLog /dev/stdout proxy env=forwarded

    <VirtualHost *:8778>
      <IfVersion >= 2.4>
        ErrorLogFormat "%M"
      </IfVersion>
      ErrorLog /dev/stdout
      SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
      CustomLog /dev/stdout combined env=!forwarded
      CustomLog /dev/stdout proxy env=forwarded

      ## WSGI configuration
      WSGIProcessGroup placement-api
      WSGIApplicationGroup %{GLOBAL}
      WSGIPassAuthorization On
      WSGIDaemonProcess placement-api processes=3 threads=1 user=placement group=placement
      WSGIScriptAlias / /usr/bin/placement-api
    </VirtualHost>

    Alias /placement-api /usr/bin/placement-api
    <Location /placement-api>
      SetHandler wsgi-script
      Options +ExecCGI
      WSGIProcessGroup placement-api
      WSGIApplicationGroup %{GLOBAL}
      WSGIPassAuthorization On
    </Location>
  kolla-config.json: |
    {
      "command": "/usr/sbin/httpd -DFOREGROUND",
      "config_files": [
        {
          "source": "/var/lib/config-data/placement.conf",
          "dest": "/etc/placement/placement.conf",
          "owner": "root",
          "perm": "0644"
        },
        {
          "source": "/var/lib/config-data/logging.conf",
          "dest": "/etc/placement/logging.conf",
          "owner": "root",
          "perm": "0644"
        },
        {
          "source": "/var/lib/config-data/httpd.conf",
          "dest": "/etc/httpd/conf/httpd.conf",
          "owner": "root",
          "perm": "0644"
        }
      ]
    }
  logging.conf: |
    [loggers]
    keys=root

    [handlers]
    keys=stdout

    [formatters]
    keys=normal


    ###########
    # Loggers #
    ###########

    [logger_root]
    level=WARNING
    handlers=stdout

    ################
    # Log Handlers #
    ################

    [handler_stdout]
    class=StreamHandler
    level=WARNING
    formatter=normal
    args=(sys.stdout,)

    ##################
    # Log Formatters #
    ##################

    [formatter_normal]
    format=(%(name)s): %(asctime)s %(levelname)s %(message)s
  placement.conf: |
    [DEFAULT]
    log_config_append = /etc/placement/logging.conf

    [api]
    auth_strategy = keystone

    [keystone_authtoken]
    project_domain_name = Default
    user_domain_name = Default
    project_name = service
    username = placement
    password = foobar123

    www_authenticate_uri = http://keystone.apps.ostest.test.metalkube.org/
    auth_url = http://keystone.openstack.svc:5000/
    auth_type = password

    [placement_database]
    connection = mysql+pymysql://placement:password@openstack-db-mariadb.openstack.svc/placement
