apiVersion: keystone.openstack.org/v1beta1
kind: KeystoneAPI
metadata:
  name: keystone
  namespace: openstack
spec:
  containerImage: docker.io/tripleomaster/centos-binary-keystone:current-tripleo
  replicas: 1
  databaseHostname: mariadb
  secret: keystone-secret
