apiVersion: v1
kind: ConfigMap
metadata:
  name: osconfig
  namespace: openstack
data:
  clouds.yaml: |
    clouds:
      default:
        auth:
          auth_url: http://keystone.openstack.svc:5000/
          project_name: admin
          username: admin
          password: foobar123
          user_domain_name: Default
          project_domain_name: Default
        region_name: regionOne
  OS_CLOUD: default
