resource_registry:
  OS::TripleO::DeployedServer::ControlPlanePort: /usr/share/openstack-tripleo-heat-templates/deployed-server/deployed-neutron-port.yaml
  OS::TripleO::Network::Ports::ControlPlaneVipPort: /usr/share/openstack-tripleo-heat-templates/deployed-server/deployed-neutron-port.yaml
  OS::TripleO::Network::Ports::RedisVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml
  OS::TripleO::Network::Ports::OVNDBsVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml

parameter_defaults:
  NeutronPublicInterface: enp2s0
  EC2MetadataIp: 192.168.25.1

  DeployedServerPortMap:
    control_virtual_ip:
      fixed_ips:
        - ip_address: 192.168.25.100
      subnets:
        - cidr: 192.168.25.0/24
      network:
        tags:
          - 192.168.25.0/24
    controller-0-ctlplane:
      fixed_ips:
        - ip_address: 192.168.25.20
      subnets:
        - cidr: 192.168.25.0/24
      network:
        tags:
          - 192.168.25.0/24
    controller-1-ctlplane:
      fixed_ips:
        - ip_address: 192.168.25.21
      subnets:
        - cidr: 192.168.25.0/24
      network:
        tags:
          - 192.168.25.0/24
    controller-2-ctlplane:
      fixed_ips:
        - ip_address: 192.168.25.22
      subnets:
        - cidr: 192.168.25.0/24
      network:
        tags:
          - 192.168.25.0/24
