---
base_path: /home/ocp
#dev_scripts_repo: defaults to "https://github.com/openshift-metal3/dev-scripts.git"
#dev_scripts_branch: defaults to "HEAD"
#dev_scripts_repo: "https://github.com/stuggi/dev-scripts.git"
#dev_scripts_branch: "masters_schedulable"

# dev scripts switched to ipv6 per default, for now switch back
# https://github.com/openshift-metal3/dev-scripts/pull/969
ocp_ip_stack: v4

# size the OCP VM resources
ocp_num_masters: 3
# ocp_num_workers this needs to be > osp_compute_scale
# worker-0 is used to host OSP controller VM, if osp_controller_scale set to 3 then worker-0 ..2 are used.
ocp_num_workers: 5
ocp_master_memory: 16384
ocp_master_vcpu: 8
ocp_master_disk: 120
ocp_worker_memory: 8192
ocp_worker_vcpu: 4
ocp_worker_disk: 120

# list of workers that will be initially for ocp compute workers,
# will default to the last # of workers up to ocp_num_workers if unset
# E.g:
# ocp_compute_workers:
#   - worker-3

# OCP cluster name
ocp_cluster_name: ostest

# name of additional host dev pass to worker and OSP controller VMs for ctrlplane traffic
ocp_osp_host_interface: enp6s0

# Released version of the opm package from the operator-framework
opm_version: v1.12.5

# guest image used as base for OSP VMs
rhel_guest_image_url: "http://download.eng.brq.redhat.com/brewroot/packages/rhel-guest-image/8.1/423/images/rhel-guest-image-8.1-423.x86_64.qcow2"

# OSP16 compose for OSP installation of undercloud and OSP controllers
osp_compose: z2

# Container tag set in containers-prepare-parameter.yaml
osp_container_tag: 20200416.1

# root password set for OSP VMs
osp_controller_root_pwd: redhat

# number of OSP controllers to deploy, can be either 1 or 3
osp_controller_scale: 1

# number of OCP worker nodes should be OSP compute hosts
osp_compute_scale: 1

# network type for OSP, either ovs or ovn (default)
osp_network_type: ovn

# operator github url where operators repos are underneath - default https://github.com/openstack-k8s-operators
#openstack_k8s_operators_https_url: defaults to "https://github.com/openstack-k8s-operators"
#openstack_k8s_operators_nova_branch: defaults to "HEAD"
#openstack_k8s_operators_neutron_branch: defaults to "HEAD"
#openstack_k8s_operators_keystone_branch: defaults to "HEAD"
#openstack_k8s_operators_heat_branch: defaults to "HEAD"

# operator images and tag to use
nova_operator_image: quay.io/openstack-k8s-operators/nova-operator:v0.0.3
neutron_operator_image: quay.io/openstack-k8s-operators/neutron-operator:v0.0.3
compute_node_operator_image: quay.io/openstack-k8s-operators/compute-node-operator:v0.0.3
cluster_operator_image: quay.io/openstack-k8s-operators/openstack-cluster-operator:v0.0.1
keystone_operator_image: quay.io/openstack-k8s-operators/keystone-operator:v0.0.3

# olm specific
csv_version: 0.0.1

ocp_network_type: OVNKubernetes

# Default worker for the openstackclient pod
openstackclient_pod_worker: worker-0
# Default worker for the tripleo-deploy job pod
tripleo_deploy_job_worker: worker-0

# private ssh key, where {{ converged_ssh_key }}.pub is being added to the stack user of the VM image for undercloud and overcloud
converged_ssh_key: /home/ocp/.ssh/id_rsa_osp

# Tempest
tempest_enabled: true

# tempest timeout in seconds
tempest_timeout: 3600

# tempest test whitelist, if [] smoke test runs
#tempest_whitelist: []
tempest_whitelist:
  - 'tempest.api.compute.servers.test_create_server.ServersTestJSON.test_list_servers'

# worker that will host the storage for mariadb
mariadb_storage_worker: worker-0

# worker that will host the storage for rabbitmq
rabbitmq_storage_worker: worker-0
