apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: &name placement
  namespace: openstack
  labels:
    app: *name
spec:
  host: placement.apps.ostest.test.metalkube.org
  path: /
  to:
    kind: Service
    name: *name
  port:
    targetPort: api
