apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-cell1
  namespace: openstack
data:
  kolla-config-conductor.json: |
    {
      "command": "/usr/bin/nova-conductor --config-file /etc/nova/nova.conf",
      "config_files": [
        {
          "source": "/var/lib/config-data/nova.conf",
          "dest": "/etc/nova/nova.conf",
          "owner": "nova",
          "perm": "0600"
        },
        {
          "source": "/var/lib/config-data/logging.conf",
          "dest": "/etc/nova/logging.conf",
          "owner": "nova",
          "perm": "0600"
        }
      ]
    }
  kolla-config-metadata.json: |
    {
      "command": "/usr/bin/nova-api-metadata --config-file /etc/nova/nova.conf",
      "config_files": [
        {
          "source": "/var/lib/config-data/nova.conf",
          "dest": "/etc/nova/nova.conf",
          "owner": "nova",
          "perm": "0600"
        },
        {
          "source": "/var/lib/config-data/logging.conf",
          "dest": "/etc/nova/logging.conf",
          "owner": "nova",
          "perm": "0600"
        }
      ]
    }
  kolla-config-novncproxy.json: |
    {
      "command": "/usr/bin/nova-novncproxy --web /usr/share/novnc/",
      "config_files": [
        {
          "source": "/var/lib/config-data/nova.conf",
          "dest": "/etc/nova/nova.conf",
          "owner": "nova",
          "perm": "0600"
        },
        {
          "source": "/var/lib/config-data/logging.conf",
          "dest": "/etc/nova/logging.conf",
          "owner": "nova",
          "perm": "0600"
        }
      ]
    }
  logging.conf: |
    [loggers]
    keys=root

    [handlers]
    keys=stdout

    [formatters]
    keys=normal


    ###########
    # Loggers #
    ###########

    [logger_root]
    level=INFO
    handlers=stdout

    ################
    # Log Handlers #
    ################

    [handler_stdout]
    class=StreamHandler
    level=INFO
    formatter=normal
    args=(sys.stdout,)

    ##################
    # Log Formatters #
    ##################

    [formatter_normal]
    format=(%(name)s): %(asctime)s %(levelname)s %(message)s
  nova.conf: |
    [DEFAULT]
    enabled_apis = metadata
    transport_url = rabbit://cell1:passw0rd@rabbitmq.openstack.svc:5672/cell1?ssl=0
    log_config_append=/etc/nova/logging.conf

    [api_database]
    connection = mysql+pymysql://nova:password@mariadb.openstack.svc/nova_api

    [database]
    connection = mysql+pymysql://nova-cell1:password@mariadb.openstack.svc/nova_cell1

    [placement]
    region_name = regionOne
    project_domain_name = Default
    project_name = service
    auth_type = password
    user_domain_name = Default
    auth_url = http://keystone.openstack.svc:5000/
    username = placement
    password = foobar123

    [neutron]
    auth_url = http://keystone.openstack.svc:5000/
    auth_type = password
    project_domain_name = Default
    user_domain_name = Default
    region_name = regionOne
    project_name = service
    username = neutron
    password = foobar123
    service_metadata_proxy = true
    metadata_proxy_shared_secret = secretsquirrel
