apiVersion: placement.openstack.org/v1beta1
kind: PlacementAPI
metadata:
  name: placement
  namespace: openstack
spec:
  # Add fields here
  databaseHostname: mariadb
  replicas: 1
  containerImage: docker.io/tripleomaster/centos-binary-placement-api:current-tripleo
  secret: placement-secret
