apiVersion: batch/v1
kind: Job
metadata:
  name: &name rabbitmq-create-api
  namespace: &namespace openstack
spec:
  backoffLimit: 10
  template:
    metadata:
      name: *name
      namespace: *namespace
    spec:
      serviceAccountName: openstack-proto
      restartPolicy: Never
      containers:
      - name: rabbitmq
        image: docker.io/tripleomaster/centos-binary-rabbitmq:current-tripleo
        command:
        - /bin/bash
        - -c
        - |
          set -e

          # rabbitmqctl seems to suffer from frequent intermittent failures.
          # Idempotence is critical.

          # rabbitmqctl targets a specific node. We target node 0. It would
          # probably be better to do this using the management rest API:
          #   https://pulse.mozilla.org/api/
          rabbitmqctl="rabbitmqctl -l -n rabbit@rabbitmq-0.rabbitmq-cluster.openstack.svc.cluster.local"

          # add_user will fail if the user already exists, in which case this
          # race is safe because we will restart
          $rabbitmqctl authenticate_user "$RABBIT_USER" "$RABBIT_PASSWORD" || \
              $rabbitmqctl add_user "$RABBIT_USER" "$RABBIT_PASSWORD"

          if [ -z "$RABBIT_VHOST" ]; then
              RABBIT_VHOST="/"
          else
              # AFAICT this is idempotent. add_vhost of an existing vhost does
              # not fail or create an additional vhost.
              $rabbitmqctl add_vhost $RABBIT_VHOST
          fi

          $rabbitmqctl set_permissions -p "$RABBIT_VHOST" "$RABBIT_USER" ".*" ".*" ".*"
        env:
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: rabbitmq-cluster
              key: cookie
        - name: RABBIT_USER
          value: osp
        - name: RABBIT_PASSWORD
          value: passw0rd
