apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb
  namespace: openstack
data:
  config.json: |
    {
        "command": "/usr/libexec/mysqld --user=mysql",
        "config_files": [
            {
                "source": "/var/lib/config-data/galera.cnf",
                "dest": "/etc/my.cnf.d/galera.cnf",
                "owner": "root",
                "perm": "0600"
            }
        ]
    }
  init_config.json: |
    {
        "command": "/usr/local/bin/mariadb_init.sh",
        "config_files": [
            {
                "source": "/var/lib/config-data/galera.cnf",
                "dest": "/etc/my.cnf.d/galera.cnf",
                "owner": "root",
                "perm": "0600"
            },
            {
                "source": "/var/lib/config-data/mariadb_init.sh",
                "dest": "/usr/local/bin/mariadb_init.sh",
                "owner": "root",
                "perm": "0755"
            }
        ],
        "permissions": [
            {
                "path": "/var/lib/mysql",
                "owner": "mysql:mysql",
                "recurse": "true"
            }
        ]
    }
  galera.cnf: |
    [client]
    port = 3306
    socket = /var/lib/mysql/mysql.sock

    [isamchk]
    key_buffer_size = 16M

    [mysqld]
    basedir = /usr
    bind-address = 127.0.0.1
    datadir = /var/lib/mysql
    expire_logs_days = 10
    innodb_file_per_table = ON
    key_buffer_size = 16M
    max_allowed_packet = 16M
    max_binlog_size = 100M
    max_connections = 4096
    open_files_limit = 65536
    pid-file = /var/lib/mysql/mariadb.pid
    port = 3306
    query_cache_limit = 1M
    query_cache_size = 16M
    skip-external-locking
    socket = /var/lib/mysql/mysql.sock
    ssl = false
    thread_cache_size = 8
    thread_stack = 256K
    tmpdir = /tmp
    user = mysql

    [mysqld_safe]
    nice = 0
    pid-file = /var/lib/mysql/mariadb.pid
    socket = /var/lib/mysql/mysql.sock

    [mysqldump]
    max_allowed_packet = 16M
    quick
    quote-names
  mariadb_init.sh: |
    if [ -e /var/lib/mysql/mysql ]; then exit 0; fi
    #echo -e "\n[mysqld]\nwsrep_provider=none" >> /etc/my.cnf
    #kolla_set_configs
    #sudo -u mysql -E kolla_extend_start
    mkdir -p /var/lib/mysql
    mysql_install_db
    mysqld_safe --skip-networking --wsrep-on=OFF &
    timeout ${DB_MAX_TIMEOUT} /bin/bash -c 'until mysqladmin -uroot -p"${DB_ROOT_PASSWORD}" ping 2>/dev/null; do sleep 1; done'
    mysql -uroot -p"${DB_ROOT_PASSWORD}" -e "CREATE USER 'mysql'@'localhost';"
    mysql -uroot -p"${DB_ROOT_PASSWORD}" -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'mysql'@'localhost';"
    timeout ${DB_MAX_TIMEOUT} mysqladmin -uroot -p"${DB_ROOT_PASSWORD}" shutdown
