apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: openstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openstack-db-mariadb
  template:
    metadata:
      labels:
        app: openstack-db-mariadb
      namespace: openstack
    spec:
      serviceAccountName: openstack-proto
      containers:
      - name: mariadb
        image: docker.io/tripleomaster/centos-binary-mariadb:current-tripleo
        #command: ['/bin/sleep', 'infinity']
        volumeMounts:
        - mountPath: /var/lib/config-data
          readOnly: true
          name: config-data
        - mountPath: /var/lib/kolla/config_files
          readOnly: true
          name: kolla-config
        - mountPath: /var/lib/mysql
          name: lib-data
        env:
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
      volumes:
      - name: kolla-config
        configMap:
          name: mariadb
          items:
            - key: config.json
              path: config.json
      - name: kolla-config-init
        configMap:
          name: mariadb
          items:
            - key: init_config.json
              path: config.json
      - name: config-data
        configMap:
          name: mariadb
          items:
            - key: galera.cnf
              path: galera.cnf
            - key: mariadb_init.sh
              path: mariadb_init.sh
      - name: lib-data
        persistentVolumeClaim:
          claimName: mariadb
      initContainers:
      - name: mariadb-init
        image: docker.io/tripleomaster/centos-binary-mariadb:current-tripleo
        command: ["/bin/bash"]
        args:
        - -c
        - |
          # Only initialise mysqldb once
          if [ ! -f /var/lib/mysql/.kolla_bootstrap ]; then
            kolla_start
            touch /var/lib/mysql/.kolla_bootstrap
          fi
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /var/lib/config-data
          readOnly: true
          name: config-data
        - mountPath: /var/lib/kolla/config_files
          readOnly: true
          name: kolla-config-init
        - mountPath: /var/lib/mysql
          name: lib-data
        env:
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
        - name: KOLLA_BOOTSTRAP
          value: 'true'
        - name: DB_MAX_TIMEOUT
          value: '30'
        - name: DB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-admin
              key: DBRootPassword
