apiVersion: database.openstack.org/v1beta1
kind: MariaDB
metadata:
  name: mariadb
  namespace: openstack
spec:
  secret: mariadb-secret
  storageClass: host-nfs-storageclass
  storageRequest: 10G
  containerImage: docker.io/tripleomaster/centos-binary-mariadb:current-tripleo
