apiVersion: v1
kind: Service
metadata:
  name: openstack-db-mariadb
  namespace: openstack
spec:
  selector:
    app: openstack-db-mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
