---
- hosts: convergence_base
  become: true
  user: root
  any_errors_fatal: true

  tasks:
  - name: Install NFS packages
    yum:
      name: nfs-utils
      state: present

  - name: Start and enable NFS services
    systemd:
      name: nfs-server
      state: started
      enabled: yes

  - name: Create NFS share
    file:
      path: /home/nfs
      state: directory
      mode: '777'
      group: nobody
      owner: nobody

  - name: Configure exports file
    lineinfile:
      path: /etc/exports
      line: '/home/nfs *(rw,sync,no_root_squash)'

  - name: Export NFS share to the server
    command: "exportfs -r"

  - name: open nfsv4 port 2049/tcp (pemanent config)
    firewalld:
      zone: libvirt
      port: 2049/tcp
      permanent: yes
      state: enabled

  - name: open nfsv4 port 2049/tcp (running config)
    firewalld:
      zone: libvirt
      port: 2049/tcp
      state: enabled
