---
- hosts: convergence_base
  gather_facts: false
  become: true
  user: root
  any_errors_fatal: true
  vars:
    pvs:
    - size: 4
      number: 16
    - size: 128
      number: 8
    - size: 128
      number: 4
      shared: true

  tasks:
  - name: Create PVs
    include_tasks: tasks/create_nfs_exports.yaml
    vars:
      exports: "{{ pvs | expand_pvs | list }}"
      group: host-nfs-storageclass
      storageclass_create: true
      storageclass_isdefault: true

  - name: Schedule fstrim on the host
    cron:
      name: fstrim
      special_time: daily
      job: "/usr/sbin/fstrim -a"
