---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - set_fact:
      repo_dir: "{{ k8s_operators_dir }}/heat-operator"

  - name: Clone openstack-k8s-operators with force=yes to be able to rerun
    git:
      repo: "{{ base_url }}/heat-operator.git"
      dest: "{{ repo_dir }}"
      version: "{{ branch }}"
      force: yes
    vars:
      base_url: "{{ openstack_k8s_operators_https_url | default('https://github.com/openstack-k8s-operators', true) }}"
      branch: "{{ openstack_k8s_operators_heat_branch | default('HEAD', true) }}"

  - name: delete heat-operator resources if they exist
    shell: |
      oc delete -n openstack -f {{ repo_dir }}/deploy/{{ item }}
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
    ignore_errors: true
    loop:
      - operator.yaml
      - crds/heat.openstack.org_v1_heat_cr.yaml
      - crds/heat.openstack.org_heats_crd.yaml
      - service_account.yaml
      - role_binding.yaml
      - role.yaml

  - name: delete heat-operator deployment if operator already deployed
    shell: |
      if oc get -n openstack deployments/heat-operator; then
        oc delete -n openstack deployments/heat-operator
      fi
      if oc get -n openstack deployments/heat-api; then
        oc delete -n openstack deployments/heat-api
      fi
      if oc get -n openstack deployments/heat-engine; then
        oc delete -n openstack deployments/heat-engine
      fi
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
    ignore_errors: true

  - name: create heat operator resources
    shell: |
      oc apply -n openstack -f {{ repo_dir }}/deploy/{{ item }}
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
    loop:
      - role.yaml
      - role_binding.yaml
      - service_account.yaml
      - crds/heat.openstack.org_heats_crd.yaml
      - operator.yaml
      - crds/heat.openstack.org_v1_heat_cr.yaml
