---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - set_fact:
      nova_yaml_dir: "{{ working_yamls_dir }}/nova"

  - debug:
      msg: "yamls will be written to {{ nova_yaml_dir }} locally"

  - name: Create yaml dir
    file:
      path: "{{ nova_yaml_dir }}"
      state: directory

  - name: Copy files to yaml dir
    copy:
      src: "{{ item }}"
      dest: "{{ nova_yaml_dir }}/"
    with_fileglob:
    - "ocp/nova/*"

  - name: Start nova
    shell: |
      set -e
      oc apply -n openstack -f "{{ nova_yaml_dir }}"
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: wait for cell1 novncproxy to be created
    shell: |
      oc get -n openstack deployment/nova-cell1-novncproxy
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
    register: vncproxy_deployment
    until: vncproxy_deployment is not failed
    retries: "{{ (default_timeout / 5)|int }}"
    delay: 5

  - name: wait for cell novncproxy to become available
    shell: |
      oc wait -n openstack deployment/nova-cell1-novncproxy \
          --for condition=available --timeout={{ default_timeout }}s
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
