---
- hosts: convergence_base
  become: true

  tasks:
  - name: Include variables
    include_vars: vars/default.yaml
    tags:
      - always

  - name: render {{ base_path }}/rabbitmq-storage.yaml
    template:
      src: rabbitmq-storage.yaml.j2
      dest: "{{ base_path }}/rabbitmq-storage.yaml"
      owner: ocp

  - name: create rabbitmq storage
    become_user: ocp
    shell: |
      # need to delete the pod before the pvc
      if oc get pods rabbitmq; then
        oc delete pods rabbitmq
      fi
      if oc get pvc rabbitmq; then
        oc delete pvc rabbitmq
      fi
      if oc get pv rabbitmq; then
        oc delete pv rabbitmq
      fi
      if oc get configmap rabbitmq; then
        oc delete configmap rabbitmq
      fi
      if oc get service openstack-rabbitmq; then
        oc delete service openstack-rabbitmq
      fi
      oc create -f {{ base_path }}/rabbitmq-storage.yaml
    args:
      chdir: "{{ base_path }}"
    environment:
      PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
      KUBECONFIG: "{{base_path}}/dev-scripts/ocp/{{ ocp_cluster_name }}/auth/kubeconfig"

  - name: create /var/lib/rabbitmq on {{ rabbitmq_storage_worker }}
    become_user: ocp
    shell: |
      oc debug nodes/{{ rabbitmq_storage_worker }} -- rm -rf /host/var/lib/rabbitmq
      oc debug nodes/{{ rabbitmq_storage_worker }} -- mkdir -p /host/var/lib/rabbitmq
    args:
      chdir: "{{ base_path }}"
    environment:
      PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
      KUBECONFIG: "{{base_path}}/dev-scripts/ocp/{{ ocp_cluster_name }}/auth/kubeconfig"

  - name: copy rabbitmq.yaml to {{ base_path }}
    copy:
      src: files/ocp/rabbitmq.yaml
      dest: "{{ base_path }}/rabbitmq.yaml"
      owner: ocp

  - name: create rabbitmq pod
    become_user: ocp
    shell: |
      if oc get pods rabbitmq; then
        oc delete pods rabbitmq
      fi
      oc create -f rabbitmq.yaml
    args:
      chdir: "{{ base_path }}"
    environment:
      PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
      KUBECONFIG: "{{base_path}}/dev-scripts/ocp/{{ ocp_cluster_name }}/auth/kubeconfig"
