---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - set_fact:
      mariadb_yaml_dir: "{{ working_dir }}/yamls/mariadb"

  - debug:
      msg: "yamls will be written to {{ mariadb_yaml_dir }} locally"

  - name: Create yaml dir
    file:
      path: "{{ mariadb_yaml_dir }}"
      state: directory

  - name: Copy deployment yamls to working dir
    copy:
      src: "{{ item }}"
      dest: "{{ mariadb_yaml_dir }}/"
    with_fileglob:
    - "files/ocp/mariadb/*"

  - name: Deploy mariadb
    shell: |
      oc apply -f "{{ mariadb_yaml_dir }}"
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: Create client utils in {{ working_bin_dir }}
    template:
      src: "mariadb/{{ item }}"
      dest: "{{ working_bin_dir }}/{{ item }}"
      mode: 0755
    loop:
    - mysql-admin
    - mysql-db

  - name: Wait for deployment
    shell: |
      oc wait -n openstack deployment/mariadb \
          --for condition=available --timeout=60s
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
