---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - set_fact:
      glance_yaml_dir: "{{ working_yamls_dir }}/glance"

  - debug:
      msg: "yamls will be written to {{ glance_yaml_dir }} locally"

  - name: Create yaml dir
    file:
      path: "{{ glance_yaml_dir }}"
      state: directory

  - name: Copy files to yaml dir
    copy:
      src: "{{ item }}"
      dest: "{{ glance_yaml_dir }}/"
    with_fileglob:
    - "ocp/glance/*"

  - name: Start glance
    shell: |
      set -e
      oc apply -n openstack -f "{{ glance_yaml_dir }}"
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: wait for deployment to be created
    shell: |
      oc get -n openstack deployment/glanceapi
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
    register: glance_deployment
    until: glance_deployment is not failed
    retries: "{{ (default_timeout / 5)|int }}"
    delay: 5

  - name: wait for deployment to become available
    shell: |
      oc wait -n openstack deployment/glanceapi \
          --for condition=available --timeout={{ default_timeout }}s
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
