---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - set_fact:
      placement_yaml_dir: "{{ working_yamls_dir }}/placement"

  - debug:
      msg: "yamls will be written to {{ placement_yaml_dir }} locally"

  - name: Create yaml dir
    file:
      path: "{{ placement_yaml_dir }}"
      state: directory

  - name: Copy deployment yamls to working dir
    copy:
      src: "{{ item }}"
      dest: "{{ placement_yaml_dir }}/"
    loop:
    - "ocp/placement/1"
    - "ocp/placement/2"
    - "ocp/placement/3"

  - name: Create database
    shell: |
      set -e

      oc apply -f "{{ placement_yaml_dir }}/1/"
      oc wait -n openstack job/placement-dbcreate \
          --for condition=Complete --timeout={{ default_timeout }}s
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: Create db schema
    shell: |
      set -e

      oc apply -f "{{ placement_yaml_dir }}/2/"
      oc wait -n openstack job/placement-dbsync \
          --for condition=Complete --timeout={{ default_timeout }}s
      oc wait -n openstack job/placement-service-init \
          --for condition=Complete --timeout={{ default_timeout }}s
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: Start placement
    shell: |
      set -e

      oc apply -f "{{ placement_yaml_dir }}/3/"
      oc wait -n openstack deployment/placement \
          --for condition=available --timeout={{ default_timeout }}s
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
