---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - import_role: name=git_checkout_operator
    vars:
      operator: mariadb-operator

  - name: Create yaml dir
    import_role: name=working_yaml_dir
    vars:
      name: mariadb

  - name: Copy files to yaml dir
    copy:
      src: "{{ item }}"
      dest: "{{ keystone_yaml_dir }}/"
    with_fileglob:
    - "ocp/mariadb/*"

  - name: Create db root password secret
    shell: |
      set -e

      password=$(oc get -n openstack mariadb/mariadb -o json | jq -r '.spec.rootPassword')
      oc create secret generic -n openstack mariadb-admin --dry-run -o yaml \
          --from-literal=DBRootPassword="${password}" > "{{ mariadb_yaml_dir }}/root-pwd.yaml"

      oc apply -n openstack -f "{{ mariadb_yaml_dir }}"
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: Create client utils in {{ working_bin_dir }}
    template:
      src: "mariadb/{{ item }}"
      dest: "{{ working_bin_dir }}/{{ item }}"
      mode: 0755
    loop:
    - mysql-admin
    - mysql-db

  - name: Wait for mariadb pod creation
    shell: |
      oc get -n openstack pod/mariadb
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
    register: mariadb_pod_creation
    until: mariadb_pod_creation is not failed
    retries: 20
    delay: 5

  - name: Wait for deployment
    shell: |
      oc wait -n openstack pod/mariadb --for condition=ready --timeout=60s
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
