---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - set_fact:
      repo_dir: "{{ k8s_operators_dir }}/keystone-operator"

  - name: Clone openstack-k8s-operators with force=yes to be able to rerun
    git:
      repo: "{{ base_url }}/keystone-operator.git"
      dest: "{{ repo_dir }}"
      version: "{{ branch }}"
      force: yes
    vars:
      base_url: "{{ openstack_k8s_operators_https_url | default('https://github.com/openstack-k8s-operators', true) }}"
      branch: "{{ openstack_k8s_operators_keystone_branch | default('HEAD', true) }}"

  #FIXME: this will soon be automated via keystone-operator
  - name: Add keystone service account to anyuid SCC
    shell: |
      oc adm policy add-scc-to-user anyuid -n openstack -z keystone
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: create keystone CR
    shell: |
      oc apply -n openstack \
          -f {{ repo_dir }}/deploy/crds/keystone.openstack.org_keystoneapis_cr.yaml
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
