---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - set_fact:
      repo_dir: "{{ k8s_operators_dir }}/keystone-operator"

  - import_role: name=git_checkout_operator
    vars:
      operator: keystone-operator

  #FIXME: this will soon be automated via keystone-operator
  - name: Add keystone service account to anyuid SCC
    shell: |
      oc adm policy add-scc-to-user anyuid -n openstack -z keystone
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: create keystone CR
    shell: |
      oc apply -n openstack \
          -f {{ repo_dir }}/deploy/crds/keystone.openstack.org_keystoneapis_cr.yaml
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
