---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - set_fact:
      rabbitmq_yaml_dir: "{{ working_yamls_dir }}/rabbitmq"
      config_yaml_dir: "{{ working_yamls_dir }}/rabbitmq-config"

  - debug:
      msg: "yamls will be written to {{ rabbitmq_yaml_dir }} locally"

  - name: Create yaml dirs
    file:
      path: "{{ item }}"
      state: directory
    loop:
    - "{{ rabbitmq_yaml_dir }}"
    - "{{ config_yaml_dir }}"

  - name: Copy deployment yamls to working dir
    copy:
      src: "{{ item }}"
      dest: "{{ rabbitmq_yaml_dir }}/"
    with_fileglob:
    - "files/ocp/rabbitmq/*"

  - name: Copy config yamls to working dir
    copy:
      src: "{{ item }}"
      dest: "{{ config_yaml_dir }}/"
    with_fileglob:
    - "files/ocp/rabbitmq-config/*"

  - name: Deploy rabbitmq
    shell: |
      oc apply -f "{{ rabbitmq_yaml_dir }}"

      oc wait -n openstack pod/rabbitmq-0 \
          --for condition=Ready --timeout={{ default_timeout }}s
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: Create rabbit users and vhosts
    shell: |
      oc apply -f "{{ config_yaml_dir }}"

      oc wait -n openstack job/rabbitmq-create-api \
          --for condition=Complete --timeout={{ default_timeout }}s

      oc wait -n openstack job/rabbitmq-create-cell \
          --for condition=Complete --timeout={{ default_timeout }}s
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
