---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - set_fact:
      repo_dir: "{{ k8s_operators_dir }}/mariadb-operator"

  - name: Clone openstack-k8s-operators with force=yes to be able to rerun
    git:
      repo: "{{ base_url }}/mariadb-operator.git"
      dest: "{{ repo_dir }}"
      version: "{{ branch }}"
      force: yes
    vars:
      base_url: "{{ openstack_k8s_operators_https_url | default('https://github.com/openstack-k8s-operators', true) }}"
      branch: "{{ openstack_k8s_operators_mariadb_branch | default('HEAD', true) }}"

  - name: create mariadb CR
    shell: |
      oc apply -n openstack \
          -f {{ repo_dir }}/config/samples/database_v1beta1_mariadb.yaml
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: Create client utils in {{ working_bin_dir }}
    template:
      src: "mariadb/{{ item }}"
      dest: "{{ working_bin_dir }}/{{ item }}"
      mode: 0755
    loop:
    - mysql-admin
    - mysql-db

  - name: Wait for deployment
    shell: |
      oc wait -n openstack pod/mariadb --for condition=ready --timeout=60s
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
