---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - set_fact:
      rabbitmq_yaml_dir: "{{ working_yamls_dir }}/rabbitmq"

  - debug:
      msg: "yamls will be written to {{ rabbitmq_yaml_dir }} locally"

  - name: Create yaml dir
    file:
      path: "{{ rabbitmq_yaml_dir }}"
      state: directory

  - name: Copy deployment yamls to working dir
    copy:
      src: "{{ item }}"
      dest: "{{ rabbitmq_yaml_dir }}/"
    with_fileglob:
    - "files/ocp/rabbitmq/*"

  - name: Deploy rabbitmq
    shell: |
      oc apply -f "{{ rabbitmq_yaml_dir }}"

      oc wait -n openstack deployment/rabbitmq \
          --for condition=available --timeout=60s
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
