---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - set_fact:
      repo_dir: "{{ k8s_operators_dir }}/keystone-operator"

  - import_role: name=git_checkout_operator
    vars:
      operator: keystone-operator

  #FIXME: this will soon be automated via keystone-operator
  - name: Add keystone service account to anyuid SCC
    shell: |
      oc adm policy add-scc-to-user anyuid -n openstack -z keystone
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: create keystone CR
    shell: |
      oc apply -n openstack \
          -f {{ repo_dir }}/deploy/crds/keystone.openstack.org_keystoneapis_cr.yaml
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: copy stackrc to working dir
    copy:
      src: stackrc
      dest: "{{ working_dir }}/stackrc"

  - set_fact:
      keystone_yaml_dir: "{{ working_yamls_dir }}/keystone"

  - name: Create yaml dir
    file:
      path: "{{ keystone_yaml_dir }}"
      state: directory

  - name: Copy osconfig to {{ keystone_yaml_dir }}
    copy:
      src: ocp/keystone/osconfig.yaml
      dest: "{{ keystone_yaml_dir }}/"

  - name: Create osconfig containing clouds.yaml
    shell: |
      oc apply -n openstack -f "{{ keystone_yaml_dir }}"
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
