---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  #FIXME: this will soon be automated via keystone-operator
  - name: Add keystone service account to anyuid SCC
    shell: |
      oc adm policy add-scc-to-user anyuid -n openstack -z keystone
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: Create yaml dir
    import_role: name=working_yaml_dir
    vars:
      name: keystone

  - name: Copy files to yaml dir
    copy:
      src: "{{ item }}"
      dest: "{{ keystone_yaml_dir }}/"
    with_fileglob:
    - "ocp/keystone/*"

  - name: create keystone CR and osconfig
    shell: |
      oc apply -n openstack -f "{{ keystone_yaml_dir }}"
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: copy stackrc to working dir
    copy:
      src: stackrc
      dest: "{{ working_dir }}/stackrc"

  - name: Wait for deployment to be created
    shell: |
      oc get -n openstack deployment/keystone
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
    register: keystone_deployment_creation
    until: keystone_deployment_creation is not failed
    retries: "{{ (default_timeout / 5)|int }}"
    delay: 5

  - name: Wait for deployment
    shell: |
      oc wait -n openstack deployment/keystone --for condition=Available \
          --timeout={{ default_timeout }}s
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
