---
- hosts: convergence_base
  become: true
  become_user: ocp

  vars:
    memcache_servers: ""
    rabbit_transport_url: ""

  tasks:
  - name: Include variables
    include_vars: vars/default.yaml

  - name: Create {{ base_path }}/github.com/openstack-k8s-operators
    file:
      path: "{{ base_path }}/github.com/openstack-k8s-operators/keystone-operator"
      state: directory
      mode: '0755'

  - name: Clone openstack-k8s-operators with force=yes to be able to rerun
    git:
      repo: "{{ openstack_k8s_operators_https_url | default('https://github.com/openstack-k8s-operators', true) }}/{{ item }}.git"
      dest: "{{ base_path }}/github.com/openstack-k8s-operators/{{ item }}"
      version: "{{ openstack_k8s_operators_keystone_branch | default('HEAD', true) }}"
      force: yes
    with_items:
      - keystone-operator

  - name: make sure mariadb pod is Running
    shell: |
      oc get pods mariadb -o json | jq .status.phase -r
    register: mariadb_out
    retries: 30
    delay: 2
    until: mariadb_out.stdout == "Running"
    args:
      chdir: "{{ base_path }}"
    environment:
      PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
      KUBECONFIG: "{{base_path}}/dev-scripts/ocp/{{ ocp_cluster_name }}/auth/kubeconfig"

  #FIXME: this will soon be automated via keystone-operator
  - name: Add keystone service account to anyuid SCC
    shell: |
      oc adm policy add-scc-to-user anyuid -n openstack -z keystone
    args:
      chdir: "{{ base_path }}"
    environment:
      PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
      KUBECONFIG: "{{base_path}}/dev-scripts/ocp/{{ ocp_cluster_name }}/auth/kubeconfig"

  - name: create keystone CR
    shell: |
      oc create -f {{ base_path }}/github.com/openstack-k8s-operators/keystone-operator/deploy/crds/keystone.openstack.org_keystoneapis_cr.yaml
    args:
      chdir: "{{ base_path }}"
    environment:
      PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
      KUBECONFIG: "{{base_path}}/dev-scripts/ocp/{{ ocp_cluster_name }}/auth/kubeconfig"
