---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - set_fact:
      placement_yaml_dir: "{{ working_yamls_dir }}/placement"

  - debug:
      msg: "yamls will be written to {{ placement_yaml_dir }} locally"

  - name: Create yaml dir
    file:
      path: "{{ placement_yaml_dir }}"
      state: directory

  - name: Copy files to yaml dir
    copy:
      src: "{{ item }}"
      dest: "{{ placement_yaml_dir }}/"
    with_fileglob:
    - "ocp/placement/*"

  - name: Start placement
    shell: |
      set -e
      oc apply -n openstack -f "{{ placement_yaml_dir }}"
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"

  - name: wait for deployment to be created
    shell: |
      oc get -n openstack deployment/placement
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
    register: placement_deployment
    until: placement_deployment is not failed
    retries: "{{ (default_timeout / 5)|int }}"
    delay: 5

  - name: wait for deployment to become available
    shell: |
      oc wait -n openstack deployment/placement \
          --for condition=available --timeout={{ default_timeout }}s
    environment:
      PATH: "{{ oc_env_path }}"
      KUBECONFIG: "{{ kubeconfig }}"
