# This playbook sets up the OpenShift cluster image registry for local use.
# It does primarily 3 things:
# 1) Sets the registry managementState to 'Managed'
# 2) Enables a 'defaultRoute' for the registry. This allows us to easily push images from outside the cluster.

---
- hosts: localhost

  tasks:
  - name: Include variables
    include_vars: vars/default.yaml

  - name: Get local oc facts
    include_tasks: local_oc_facts.yaml

  - name: set image registry to managed
    shell: >
      oc patch configs.imageregistry.operator.openshift.io/cluster \
          --patch '{"spec":{"managementState":"Managed"}}' --type=merge
    environment:
      KUBECONFIG: "{{ kubeconfig }}"

  - name: enable default route on image registry
    shell: >
      oc patch configs.imageregistry.operator.openshift.io/cluster \
          --patch '{"spec":{"defaultRoute":true}}' --type=merge
    environment:
      KUBECONFIG: "{{ kubeconfig }}"

  - name: Copy PVC to working dir
    copy:
      src: openshift-image-registry-pvc.yaml
      dest: "{{ working_dir }}/"

  - name: Create PVC
    shell: |
      oc apply -f "{{ working_dir }}/openshift-image-registry-pvc.yaml"
    environment:
      KUBECONFIG: "{{ kubeconfig }}"

  - name: configure storage pvc for openshift-image-registry
    shell: >
      oc patch configs.imageregistry.operator.openshift.io cluster --type merge \
          --patch '{"spec":{"storage":{"pvc":{"claim": "openshift-image-registry-pvc"}}}}'
    environment:
      KUBECONFIG: "{{ kubeconfig }}"

  - name: wait for image registry to be deployed
    shell: >
      oc wait --for condition=available -n openshift-image-registry deployment/image-registry
    environment:
      KUBECONFIG: "{{ kubeconfig }}"

  - name: add OpenShift CA cert to local disk (so we can access the image registry)
    shell: >
      cat $KUBECONFIG | grep certificate-authority-data | head -n 1 | cut -f 6 -d " " | base64 -d > /etc/ssl/certs/openshift.pem
    environment:
      KUBECONFIG: "{{ kubeconfig }}"
    become_user: root
    become: true    
