---
- hosts: convergence_base
  gather_facts: false
  become: true
  user: root
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
  - block:
    - name: Remove OCS from OCP cluster
      shell: |
        oc patch cephcluster storagecluster-cephcluster --type='json' -p='[{"op": "replace", "path": "/metadata/finalizers", "value":[]}]' -n openshift-storage;
        oc patch storagecluster storagecluster --type='json' -p='[{"op": "replace", "path": "/metadata/finalizers", "value":[]}]' -n openshift-storage;
        oc patch backingstore noobaa-default-backing-store --type='json' -p='[{"op": "replace", "path": "/metadata/finalizers", "value":[]}]' -n openshift-storage;
        oc delete namespace/openshift-storage
      register: remove_ocs
      failed_when: remove_ocs.stderr != "" and "not found" not in remove_ocs.stderr
      environment:
        PATH: "{{ oc_env_path }}"
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Remove local storage from OCP cluster
      shell: |
        oc patch localvolume local-disks --type='json' -p='[{"op": "replace", "path": "/metadata/finalizers", "value":[]}]' -n local-storage;
        oc delete namespace/local-storage
      register: remove_local_storage
      failed_when: remove_local_storage.stderr != "" and "not found" not in remove_local_storage.stderr
      environment:
        PATH: "{{ oc_env_path }}"
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Scale storage machineset to 0
      shell: oc scale machineset/{{ ocp_cluster_name }}-storage-0 --replicas=0 -n openshift-machine-api
      register: scale_machineset
      failed_when: scale_machineset.stderr != "" and "not found" not in scale_machineset.stderr
      environment:
        PATH: "{{ oc_env_path }}"
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Wait for storage nodes to be de-provisioned
      shell: oc get nodes
      retries: 300
      register: storage_nodes_removed
      until: "'{{ ocp_cluster_name }}-storage-' not in storage_nodes_removed.stdout"
      environment:
        PATH: "{{ oc_env_path }}"
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Delete storage machineset
      shell: oc delete machineset/{{ ocp_cluster_name }}-storage-0 -n openshift-machine-api
      register: delete_machineset
      failed_when: delete_machineset.stderr != "" and "not found" not in delete_machineset.stderr
      environment:
        PATH: "{{ oc_env_path }}"
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Remove storage baremetal hosts from OCP
      shell: oc delete bmh/{{ ocp_cluster_name }}-storage-{{ item }} -n openshift-machine-api
      register: delete_bmhs
      failed_when: delete_bmhs.stderr != "" and "not found" not in delete_bmhs.stderr
      environment:
        PATH: "{{ oc_env_path }}"
        KUBECONFIG: "{{ kubeconfig }}"
      with_items:
        - 0
        - 1
        - 2

    - name: Stop and delete storage VM vbmcs
      shell: |
        vbmc stop {{ item }};
        vbmc delete {{ item }}
      with_items:
        - "{{ ocp_cluster_name }}-storage-0"
        - "{{ ocp_cluster_name }}-storage-1"
        - "{{ ocp_cluster_name }}-storage-2"

    - name: Destroy and undefine storage VMs
      shell: |
        virsh destroy {{ item }};
        virsh undefine {{ item }}
      with_items:
        - "{{ ocp_cluster_name }}-storage-0"
        - "{{ ocp_cluster_name }}-storage-1"
        - "{{ ocp_cluster_name }}-storage-2"

    - name: Remove storage VM qcow2s
      command: "virsh vol-delete {{ item }}.qcow2 --pool=default"
      with_items:
        - "{{ ocp_cluster_name }}-storage-0"
        - "{{ ocp_cluster_name }}-storage-1"
        - "{{ ocp_cluster_name }}-storage-2"

    - name: Read host {{ ocs_device }} information
      parted: device={{ ocs_device }} unit=MiB
      register: device_info

    - name: Remove partitions on host {{ ocs_device }}
      parted:
        device: '{{ ocs_device }}'
        number: '{{ item.num }}'
        state: absent
      loop: '{{ device_info.partitions }}'