#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars_files: "vars/default.yaml"

  roles:
  - oc_local

  tasks:
    - name: Cleanup of OpenStack
      environment:
        PATH: "{{ oc_env_path }}"
        KUBECONFIG: "{{ kubeconfig }}"
      block:

        - name: delete yamls from working dir
          file:
            path: "{{ working_yamls_dir }}"
            state: absent

        - name: get worker-osp node name
          shell: |
            oc get nodes | grep worker-osp | cut -d ' ' -f1
          register: worker_osp_node

        - name: get worker-osp machine name
          shell: |
            oc get -n openshift-machine-api machines | grep worker-osp | cut -d ' ' -f1
          register: worker_osp_machine

        - name: get worker-osp baremetalhost name
          shell: |
            oc get -n openshift-machine-api bmh | grep worker-osp | cut -d ' ' -f1
          register: worker_osp_bmh

        - name: scale osp machineset to 0
          shell: |
            if oc get -n openshift-machine-api machineset ostest-worker-osp; then
              oc scale -n openshift-machine-api --replicas 0 machineset ostest-worker-osp --timeout 3m
            fi

        - name: wait until worker-osp gets deprovisioned
          shell: |
            set -e -o pipefail

            if oc get -n openshift-machine-api machineset ostest-worker-osp 2>/dev/null 1>/dev/null; then
              oc get -n openshift-machine-api machineset/{{ ocp_cluster_name }}-worker-osp -o json | jq -re '.status.replicas'
            else
              echo 0
            fi
          register: worker_osp_ready
          until: worker_osp_ready is not failed and worker_osp_ready.stdout == "0"
          delay: 3
          retries: 60
          tags:
          - wait

        - name: delete worker-osp node {{ worker_osp_node.stdout }}
          shell: |
            oc delete --ignore-not-found node {{ worker_osp_node.stdout }}
          when: worker_osp_node.stdout != ""

        - name: delete osp machineset
          shell: >
            oc delete --ignore-not-found -n openshift-machine-api machineset ostest-worker-osp

        - name: delete openstack.org CRD's
          shell: >
            oc get crds | grep openstack.org | cut -f1 -d ' ' | xargs -r -t oc delete crds --cascade

        - name: delete openstack namespace
          shell: >
              oc delete --ignore-not-found namespace openstack
