#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars_files: "vars/default.yaml"

  roles:
  - oc_local

  tasks:
    - name: Cleanup of OpenStack
      environment:
        PATH: "{{ oc_env_path }}"
        KUBECONFIG: "{{ kubeconfig }}"
      block:

        - name: scale osp machineset to 0
          shell: |
            if oc get -n openshift-machine-api machineset ostest-worker-osp-0; then
              os scale --replicas 0 machineset ostest-worker-osp-0 --timeout 3m
            fi

        - name: delete osp machineset
          shell: >
            oc delete --ignore-not-found -n openshift-machine-api machineset ostest-worker-osp-0

        - name: delete openstack.org CRD's
          shell: >
            oc get crds | grep openstack.org | cut -f1 -d ' ' | xargs -r -t oc delete crds --cascade

        - name: delete openstack namespace
          shell: >
              oc delete --ignore-not-found namespace openstack
