#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars_files: "vars/default.yaml"

  roles:
  - oc_local

  tasks:
    - name: Cleanup of OpenStack
      environment:
        PATH: "{{ oc_env_path }}"
        KUBECONFIG: "{{ kubeconfig }}"
      block:
        - name: switch to openstack project/namespace
          shell: >
            oc project openstack

        - name: delete openstack.org CRD's
          shell: >
            oc get crds | grep openstack.org | cut -f1 -d ' ' | xargs -t oc delete crds --cascade

        - name: delete openstack namespace
          shell: >
            oc delete namespace openstack
