apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name neutron-api
  namespace: &namespace openstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
      namespace: *namespace
    spec:
      serviceAccountName: openstack-proto
      containers:
        - name: neutron-kolla
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: "COPY_ALWAYS"
          image: tripleotrain/rhel-binary-neutron-server-ovn:current-tripleo
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          command:
            - /bin/bash
            - -c
            - exec kolla_start
          volumeMounts:
            - mountPath: /var/lib/config-data
              readOnly: true
              name: config-data
            - mountPath: /var/lib/kolla/config_files
              readOnly: true
              name: kolla-config
      volumes:
        - name: kolla-config
          configMap:
            name: neutron-api
            items:
              - key: kolla-config.json
                path: config.json
        - name: config-data
          configMap:
            name: neutron-api
            defaultMode: 0444
            items:
              - key: neutron.conf
                path: neutron.conf
              - key: logging.conf
                path: logging.conf
