apiVersion: batch/v1
kind: Job
metadata:
  name: &name neutron-api-dbcreate
  namespace: &namespace openstack
spec:
  backoffLimit: 4
  template:
    metadata:
      name: *name
      namespace: *namespace
    spec:
      restartPolicy: Never
      containers:
        - name: mariadb-client
          image: docker.io/tripleomaster/centos-binary-mariadb:current-tripleo
          env:
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mariadb-admin
                  key: DBRootPassword
          command:
            - /bin/bash
            - -c
            - |
              mysql -h mariadb.openstack.svc -u root -P 3306 -e "CREATE DATABASE IF NOT EXISTS neutron; GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY 'password';GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY 'password';"
