apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &name nova-api-super-conductor
  namespace: &namespace openstack
spec:
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      name: *name
      namespace: *namespace
      labels:
        app: *name
    spec:
      containers:
      - image: tripleotrain/rhel-binary-nova-conductor:current-tripleo
        name: nova-api-kolla
        env:
        - name: KOLLA_CONFIG_STRATEGY
          value: "COPY_ALWAYS"
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /var/lib/config-data
          readOnly: true
          name: config-data
        - mountPath: /var/lib/kolla/config_files
          readOnly: true
          name: kolla-config
      volumes:
      - name: kolla-config
        configMap:
          name: nova-api
          defaultMode: 0444
          items:
          - key: kolla-config-super-conductor.json
            path: config.json
      - name: config-data
        configMap:
          name: nova-api
          defaultMode: 0444
          items:
          - key: nova.conf
            path: nova.conf
          - key: logging.conf
            path: logging.conf
